# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import ml_service_pb2 as proto_dot_ml__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/ml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub(object):
    """ML Service for inference operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/ml_service.MLService/Classify',
                request_serializer=proto_dot_ml__service__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=proto_dot_ml__service__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/ml_service.MLService/Embed',
                request_serializer=proto_dot_ml__service__pb2.EmbedRequest.SerializeToString,
                response_deserializer=proto_dot_ml__service__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.Route = channel.unary_unary(
                '/ml_service.MLService/Route',
                request_serializer=proto_dot_ml__service__pb2.RouteRequest.SerializeToString,
                response_deserializer=proto_dot_ml__service__pb2.RouteResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ml_service.MLService/HealthCheck',
                request_serializer=proto_dot_ml__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_ml__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class MLServiceServicer(object):
    """ML Service for inference operations
    """

    def Classify(self, request, context):
        """Classify a prompt to determine task complexity and routing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Generate embeddings for text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Route(self, request, context):
        """Route a request to optimal model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=proto_dot_ml__service__pb2.ClassifyRequest.FromString,
                    response_serializer=proto_dot_ml__service__pb2.ClassifyResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=proto_dot_ml__service__pb2.EmbedRequest.FromString,
                    response_serializer=proto_dot_ml__service__pb2.EmbedResponse.SerializeToString,
            ),
            'Route': grpc.unary_unary_rpc_method_handler(
                    servicer.Route,
                    request_deserializer=proto_dot_ml__service__pb2.RouteRequest.FromString,
                    response_serializer=proto_dot_ml__service__pb2.RouteResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_ml__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_ml__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml_service.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ml_service.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService(object):
    """ML Service for inference operations
    """

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MLService/Classify',
            proto_dot_ml__service__pb2.ClassifyRequest.SerializeToString,
            proto_dot_ml__service__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MLService/Embed',
            proto_dot_ml__service__pb2.EmbedRequest.SerializeToString,
            proto_dot_ml__service__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MLService/Route',
            proto_dot_ml__service__pb2.RouteRequest.SerializeToString,
            proto_dot_ml__service__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_service.MLService/HealthCheck',
            proto_dot_ml__service__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_ml__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
