package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"time"

	"github.com/smartcp/bifrost/internal/models"
)

// RegisterTool is the resolver for the registerTool field.
func (r *mutationResolver) RegisterTool(ctx context.Context, input models.RegisterToolInput) (*models.Tool, error) {
	return r.ToolRegistry.RegisterTool(ctx, &input)
}

// UpdateTool is the resolver for the updateTool field.
func (r *mutationResolver) UpdateTool(ctx context.Context, id string, input models.UpdateToolInput) (*models.Tool, error) {
	return r.ToolRegistry.UpdateTool(ctx, id, &input)
}

// DeleteTool is the resolver for the deleteTool field.
func (r *mutationResolver) DeleteTool(ctx context.Context, id string) (bool, error) {
	err := r.ToolRegistry.DeleteTool(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// ExecuteTool is the resolver for the executeTool field.
func (r *mutationResolver) ExecuteTool(ctx context.Context, input models.ExecuteToolInput) (*models.ExecutionResult, error) {
	return r.Execution.ExecuteTool(ctx, &input)
}

// Tools is the resolver for the tools field.
func (r *queryResolver) Tools(ctx context.Context, category *string, tags []string, limit *int, offset *int) ([]*models.Tool, error) {
	l := 100
	if limit != nil {
		l = *limit
	}
	o := 0
	if offset != nil {
		o = *offset
	}
	return r.ToolRegistry.ListTools(ctx, category, tags, l, o)
}

// Tool is the resolver for the tool field.
func (r *queryResolver) Tool(ctx context.Context, id string) (*models.Tool, error) {
	return r.ToolRegistry.GetTool(ctx, id)
}

// Route is the resolver for the route field.
func (r *queryResolver) Route(ctx context.Context, request string, context *string) (*models.RoutingDecision, error) {
	return r.ToolRouting.RouteRequest(ctx, request, context)
}

// SemanticSearch is the resolver for the semanticSearch field.
func (r *queryResolver) SemanticSearch(ctx context.Context, query string, limit *int, threshold *float64) ([]*models.SearchResult, error) {
	l := 10
	if limit != nil {
		l = *limit
	}
	t := 0.7
	if threshold != nil {
		t = *threshold
	}
	return r.Resolver.SemanticSearch.Search(ctx, query, l, t)
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "OK", nil
}

// ToolEvents is the resolver for the toolEvents field.
func (r *subscriptionResolver) ToolEvents(ctx context.Context, toolID *string) (<-chan *models.ToolEvent, error) {
	ch := make(chan *models.ToolEvent, 1)

	// Send initial event
	go func() {
		defer close(ch)
		event := &models.ToolEvent{
			EventType: "connected",
			Timestamp: time.Now(),
		}
		select {
		case ch <- event:
		case <-ctx.Done():
			return
		}
	}()

	return ch, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *toolResolver) CreatedAt(ctx context.Context, obj *models.Tool) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *toolResolver) UpdatedAt(ctx context.Context, obj *models.Tool) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// Timestamp is the resolver for the timestamp field.
func (r *toolEventResolver) Timestamp(ctx context.Context, obj *models.ToolEvent) (string, error) {
	return obj.Timestamp.Format(time.RFC3339), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Tool returns ToolResolver implementation.
func (r *Resolver) Tool() ToolResolver { return &toolResolver{r} }

// ToolEvent returns ToolEventResolver implementation.
func (r *Resolver) ToolEvent() ToolEventResolver { return &toolEventResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type toolResolver struct{ *Resolver }
type toolEventResolver struct{ *Resolver }
